# Generated by Django 3.2 on 2022-01-10 01:58

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_num', models.CharField(max_length=32, verbose_name='版本号')),
                ('version_name', models.CharField(blank=True, max_length=128, verbose_name='版本名称')),
                ('version_desc', models.TextField(blank=True, max_length=1024, verbose_name='版本描述')),
                ('version_state', models.BooleanField(choices=[(0, 'false'), (1, 'true')], default=True, verbose_name='版本状态')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建日期')),
                ('creator', models.ForeignKey(default=django.contrib.auth.models.User, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '版本列表',
                'verbose_name_plural': '版本列表',
                'db_table': 'version',
            },
        ),
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=32, verbose_name='项目名称')),
                ('project_desc', models.TextField(blank=True, max_length=1024, verbose_name='项目描述')),
                ('project_state', models.BooleanField(choices=[(0, 'false'), (1, 'true')], default=True, verbose_name='项目状态')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建日期')),
                ('creator', models.ForeignKey(default=django.contrib.auth.models.User, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '项目列表',
                'verbose_name_plural': '项目列表',
                'db_table': 'project',
            },
        ),
    ]
