# Generated by Django 3.2 on 2022-01-10 01:58

import apiManage.models
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projectManage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='haeder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_name', models.CharField(max_length=32, verbose_name='请求头名称')),
                ('header_data', models.CharField(choices=[("{'Content-Type': 'application/x-www-form-urlencoded'}", "{'Content-Type': 'application/x-www-form-urlencoded'}"), ("{'Content-Type': 'application/json'}", "{'Content-Type': 'application/json'}"), ("{'Content-Type': 'multipart/form-data'}", "{'Content-Type': 'multipart/form-data'}"), ('{}', '{}'), ("{'Content-Type': 'text/html'}", "{'Content-Type': 'text/html'}"), ("{'x-requested-with': 'XMLHttpRequest'}", "{'x-requested-with': 'XMLHttpRequest'}")], default=("{'Content-Type': 'application/x-www-form-urlencoded'}", "{'Content-Type': 'application/x-www-form-urlencoded'}"), max_length=2048)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='创建日期')),
                ('creator', models.ForeignKey(default=django.contrib.auth.models.User, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '请求header',
                'verbose_name_plural': '请求header列表',
                'db_table': 'header',
            },
        ),
        migrations.CreateModel(
            name='environment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('environment_name', models.CharField(max_length=32, verbose_name='环境名称')),
                ('environment_desc', models.CharField(blank=True, max_length=1024, verbose_name='环境描述')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建日期')),
                ('creator', models.ForeignKey(default=django.contrib.auth.models.User, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '环境列表',
                'verbose_name_plural': '环境列表',
                'db_table': 'environment',
            },
        ),
        migrations.CreateModel(
            name='domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(max_length=1024, verbose_name='域名名称')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='创建日期')),
                ('creator', models.ForeignKey(default=django.contrib.auth.models.User, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('domain_environment', models.ForeignKey(default=apiManage.models.environment, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiManage.environment', verbose_name='域名关联的环境id')),
                ('domain_project', models.ForeignKey(default='projectManage.models.project', null=True, on_delete=django.db.models.deletion.SET_NULL, to='projectManage.project', verbose_name='域名关联的项目')),
            ],
            options={
                'verbose_name': '域名列表',
                'verbose_name_plural': '域名列表',
                'db_table': 'domain',
            },
        ),
        migrations.CreateModel(
            name='api',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_name', models.CharField(blank=True, max_length=128, verbose_name='接口名称')),
                ('api_req_method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('DELETE', 'DELETE')], default=('GET', 'GET'), max_length=128, verbose_name='请求方式')),
                ('api_url', models.CharField(max_length=1024, verbose_name='请求url')),
                ('api_request_data', models.TextField(blank=True, default=None, null=True, verbose_name='请求参数')),
                ('api_domain', models.ForeignKey(default=apiManage.models.domain, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiManage.domain', verbose_name='请求域名')),
                ('api_header', models.ForeignKey(default=apiManage.models.haeder, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiManage.haeder', verbose_name='请求header')),
                ('api_version', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projectManage.version', verbose_name='项目关联的版本信息')),
            ],
            options={
                'verbose_name': '接口列表',
                'verbose_name_plural': '接口列表',
                'db_table': 'api',
            },
        ),
    ]
