# Generated by Django 3.2 on 2022-01-10 01:58

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apiManage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='caseReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caseReport_name', models.CharField(max_length=128, verbose_name='测试报告名称')),
                ('caseReport_start_time', models.DateTimeField(default=django.utils.timezone.now, max_length=128, verbose_name='测试报告开始执行时间')),
                ('caseReport_end_time', models.DateTimeField(default=django.utils.timezone.now, max_length=128, verbose_name='测试报告结束执行时间')),
                ('caseReport_run_time', models.IntegerField(default=0, verbose_name='测试报告执行时间')),
                ('case_run_num', models.FloatField(default=0.0, editable=False, verbose_name='本次运行用例个数')),
                ('case_skip_num', models.IntegerField(default=0, editable=False, verbose_name='本次跳过运行用例个数')),
                ('case_pass_num', models.IntegerField(default=0, editable=False, verbose_name='用例通过个数')),
                ('case_fail_num', models.IntegerField(default=0, editable=False, verbose_name='用例失败个数')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='创建日期')),
                ('creator', models.ForeignKey(default=django.contrib.auth.models.User, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '测试报告',
                'verbose_name_plural': '测试报告',
                'db_table': 'case_report',
            },
        ),
        migrations.CreateModel(
            name='caseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caseLog_name', models.CharField(editable=False, max_length=128, verbose_name='用例日志名称')),
                ('caseLog_caseId', models.IntegerField(editable=False, verbose_name='关联的测试用例')),
                ('caseLog_resp', models.TextField(blank=True, default='', editable=False, verbose_name='请求响应')),
                ('caseLog_res_status_code', models.IntegerField(blank=True, editable=False, verbose_name='请求响应code')),
                ('caseLog_res_time', models.FloatField(default=0.0, editable=False, verbose_name='请求响应时间')),
                ('caseLog_type', models.CharField(default='', help_text="'debug:用例调试日志,info:用例运行日志", max_length=32, verbose_name='用例日志类型')),
                ('caseLog_run_status', models.IntegerField(choices=[(0, 'false'), (1, 'true')], default=False, editable=False, verbose_name='api最新执行状况')),
                ('caseLog_case_is_pass', models.BooleanField(default=False, editable=False, verbose_name='用例是否执行通过')),
                ('caseLog_last_run_lable', models.IntegerField(default=0, help_text='只有最近一次执行的用例会将标记更新为1，其余情况下为0', verbose_name='用例最新执行日志标识')),
                ('caselog_remark', models.TextField(blank=True, verbose_name='备注')),
                ('caseLog_report_id', models.IntegerField(blank=True, null=True, verbose_name='测试日志关联的测试报告id')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='创建日期')),
                ('creator', models.ForeignKey(default=django.contrib.auth.models.User, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '用例执行日志',
                'verbose_name_plural': '用例执行日志',
                'db_table': 'case_log',
            },
        ),
        migrations.CreateModel(
            name='case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_name', models.CharField(max_length=128, unique=True, verbose_name='用例名称')),
                ('case_desc', models.CharField(blank=True, max_length=1024, verbose_name='用例描述')),
                ('case_is_run', models.BooleanField(choices=[(0, 'false'), (1, 'true')], default=(1, 'true'), verbose_name='用例是否执行')),
                ('case_preposition_step', models.TextField(blank=True, default='', verbose_name='用例前置步骤')),
                ('case_postposition_step', models.TextField(blank=True, default='', verbose_name='用例后置步骤')),
                ('case_assert_content', models.CharField(blank=True, help_text='根据断言类型,可能使用不同的值：jsonpath/正则/sql/对象断言时，分别为jsonpath表达式/正则表达式/sql语句/dict', max_length=1024, verbose_name='断言文本内容')),
                ('case_expect_result', models.CharField(blank=True, max_length=1024, verbose_name='用例预期结果')),
                ('case_assert_type', models.CharField(choices=[('contains', '文本包含'), ('regEx', '正则表达式'), ('jsonPath', 'json解析'), ('sql', 'sql断言'), ('dict', '字典断言')], default=('contains', '文本包含'), max_length=64, verbose_name='断言类型')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='创建日期')),
                ('case_api_ids', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiManage.api', verbose_name='关联的接口集合')),
                ('case_depend_case', models.ForeignKey(blank=True, default='caseManage.models.case', null=True, on_delete=django.db.models.deletion.SET_NULL, to='caseManage.case', verbose_name='依赖的用例')),
                ('creator', models.ForeignKey(default=django.contrib.auth.models.User, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '用例列表',
                'verbose_name_plural': '用例列表',
                'db_table': 'case',
            },
        ),
    ]
